version: '2'

services:
  engine:
    build: engine
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "80:80"
      - "443:443"
  db:
    build: db
    environment:
      MYSQL_DATABASE: drupal8
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/db/var/lib/mariadb:/var/lib/mysql
